import Head from 'next/head';

export default function Home() {
  return (
    <Head>
      <title>작가의 정원</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
/*
http://localhost:3000/completedRecruitment
http://localhost:3000/createdNovel
http://localhost:3000/createdUser
http://localhost:3000/login
http://localhost:3000/novel/detail
http://localhost:3000/novel/list
http://localhost:3000/novel/read
http://localhost:3000/novel
http://localhost:3000/recruitment
http://localhost:3000/recruitment/detail/1
http://localhost:3000/signUp
http://localhost:3000/user/passwd
http://localhost:3000/write/detail
http://localhost:3000/write/info
http://localhost:3000/write/post
http://localhost:3000/



http://34.83.68.228/completedRecruitment
http://34.83.68.228/createdNovel
http://34.83.68.228/createdUser
http://34.83.68.228/login
http://34.83.68.228/novel/detail
http://34.83.68.228/novel/list
http://34.83.68.228/novel/read
http://34.83.68.228/novel
http://34.83.68.228/recruitment
http://34.83.68.228/recruitment/detail/1
http://34.83.68.228/signUp
http://34.83.68.228/user/passwd
http://34.83.68.228/write/detail
http://34.83.68.228/write/info
http://34.83.68.228/write/post
http://34.83.68.228/
*/
