import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import { globalStyle } from 'lib/stitches.config';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  globalStyle();
  return (
    <>
      <Head>
        <title>작가의 정원</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </>
  );
}
